#!/bin/bash

. ./assert.sh/assert.sh

testdir=$(pwd)
gitrpmversion=$(readlink -m "$testdir"/../git-rpm-version)

for test in "$testdir"/test-*; do
    tempdir=$(mktemp -d)
    pushd "$tempdir" >/dev/null
    . "$test"
    assert_end $(basename "$test")
    popd >/dev/null
done
